- Main.tscn
- Scripts/Canvas.gd
- Scripts/Main.gd
- project.godot
Added flip horizontal and vertical to the edit menu, and also to the shortcuts Shift + H and Shift + V.
> [Feature] Added flip horizontal/vertical

- Misc/Linux/com.orama-interactive.Pixelorama.desktop
- Misc/Linux/com.orama-interactive.Pixelorama.xml
These could be pulled into a Flatpak in the future.
> Add `.desktop` and AppStream metadata files for Linux integration

- Scripts/Canvas.gd
> Don't draw blue rectangle arround selected pixel when picking color

- Scripts/Canvas.gd
This is another attempt to workarround the bug reported in #10, although it doesn't address the real cause of it. I think there may be a bug in the engine itself, given the strage steps that cause the problem.
> Another attemt to workarround flood_fill bug

- Scripts/Canvas.gd
> Added custom blend function to workarround godot's blend rect issue

- Scripts/Main.gd
> Fix compatibility with Godot 3.1

- project.godot
The description will be displayed when hovering the project in the Project Manager (in 3.2alpha1 and later).
> Add a project description

- Main.tscn
- Prefabs/FrameButton.tscn
- Prefabs/LayerContainer.tscn
- Themes & Styles/Main Theme.tres
I changed the Main Theme so that it's more consistent, without gradients and with less colors for easier use.
> Fixed theme inconsistencies

- Scripts/Main.gd
may be you'd like to rename `sub_key_mask`
but now it's work better (more comfortable) on macOS
> [hotkeys] Add cmd-key supporting for macOS, closes #67

- Main.tscn
- Themes & Styles/Main Theme/Original Theme.tres
- Themes & Styles/Main Theme/OriginalTopMenuStyle.tres
- project.godot
> Added Hsliders, switched some colors, New "Original theme"

- Themes & Styles/Light Theme/Light Theme.tres
- Themes & Styles/Light Theme/LightRulerStyle.tres
- Themes & Styles/Light Theme/LightTopMenuStyle.tres
Still a lot of work to be done on it but that's an initial idea of that theme
> Started working on Light Theme

- Scripts/Global.gd
i had tried to run it with Godot 3.2 Beta 4 and master (d711c57d76), but Godot complaint about a wrong type.
> Fix wrong type to run with Godot 3.2 beta

- Main.tscn
- Scripts/Main.gd
> Fix LineEdit holding focus when it's not required

- Prefabs/Dialogs/RotateImage.gd
- Scripts/Global.gd
It upscales the image, rotates it and then downscales it.
> Rotsprite-like Rotation

- .gitmodules
- Prefabs/Dialogs/ExportDialog.tscn
- Scripts/AnimationTimeline.gd
- Scripts/Dialogs/ExportDialog.gd
- Translations/Translations.pot
- project.godot
I tested it for some time but I would suggest not to merge until it's clear that everything works correctly on all supported platforms.
Supported platforms for now are Windows and Linux, both 32 and 64 bit. Some testing would be appreciated on 32 bit since all OS's I have are 64 bit.
To clone the plugin submodule: git submodule update --init
Plugin contains compiled GDNative libraries so no compilation should be needed.
> Add GIF export for Windows and Linux

- Prefabs/Dialogs/PreferencesDialog.tscn
- Scripts/Dialogs/PreferencesDialog.gd
Updated PreferencesDialog.tscn and PreferencesDialog.gd
> Added the left and right tool icon option to be saved and restored on  startup

- Scripts/CameraMovement.gd
- Scripts/Global.gd
Basically the title.
This patch means you can navigate the canvas area using the arrow keys with shift/control for moving them around ^.^
nya
> Made arrow keys (with shift and control for speedup) work ^.^ nyaaa

- Prefabs/Dialogs/PreferencesDialog.tscn
- Scripts/Dialogs/PreferencesDialog.gd
- Scripts/Main.gd
- Translations/Translations.pot
Just a small cleanup of the preference dialog visuals.
I also added missing hints and translations.
> Cleanup preference dialog

- Main.tscn
- Prefabs/Dialogs/PreferencesDialog.tscn
- Scripts/Dialogs/PreferencesDialog.gd
- Scripts/Global.gd
- Scripts/Main.gd
- Translations/Translations.pot
- project.godot
Adds a switch colors shortcut to preferences.
> Switch colors shortcut

- Translations/Translations.pot
Completed the hole in translation for the new open last project on startup or at will feature.
> Translation completion for new feature.

- src/Autoload/Import.gd
Adds support for the newer variant of gpl files where "Name: " is used for palette name, and extracts palette name from comment if present (some converter/exporter must do this, as it was present in 4 of the palettes I had downloaded).
Also supports palettes where no name is supplied for the colours.  
These changes fix failed imports of palettes using this new format, and palettes with unnamed colours.  
Tested on a handful of GIMP palettes and appears to work fine.
> Gimp palette import fixes

- project.godot
- src/Autoload/DrawingAlgos.gd
- src/Canvas.gd
- src/Classes/Drawers.gd
The pixel perfect don't work correctly when brush size is not 1, I forced it disabled when brush size is not 1.
> Move pixel perfect and mirror code to drawers class

- project.godot
- src/Autoload/DrawingAlgos.gd
- src/Autoload/Global.gd
- src/Autoload/Import.gd
- src/Autoload/OpenSave.gd
- src/Canvas.gd
- src/Classes/Project.gd
- src/Main.gd
- src/Preferences/HandleThemes.gd
- src/SelectionRectangle.gd
- src/UI/BrushButton.gd
- src/UI/ColorAndToolOptions.gd
- src/UI/Dialogs/CreateNewImage.gd
- src/UI/Dialogs/ExportDialog.gd
- src/UI/Dialogs/HSVDialog.gd
- src/UI/Dialogs/ImportSprites.gd
- src/UI/Dialogs/OutlineDialog.gd
- src/UI/Dialogs/ScaleImage.gd
- src/UI/Rulers/Guides.gd
- src/UI/Timeline/AnimationTimeline.gd
- src/UI/Timeline/CelButton.gd
- src/UI/Timeline/FrameTagDialog.gd
- src/UI/Timeline/LayerButton.gd
- src/UI/TransparentChecker.gd
With the creation of the new Project class, that takes some variables away from Global and leads the way to multiple tab support, I think we have reached the end of the refactoring phase. At least, for me. If you still have more refactoring proposals, feel free to open more PRs to master! I will start working on multiple tab support next. This PR closes #232.
> Last refactoring merge

- src/Autoload/DrawingAlgos.gd
- src/Canvas.gd
Also added hovering brush preview for same. 
Fixes #65
> Added the ability to draw on Tiling Mode Previews

- src/Autoload/DrawingAlgos.gd
- src/Canvas.gd
Using line2d, we dunno where the actual pixel is drawn. I changed it to plot the line like the circle brush.
> Change the line2d to plot line pixel when drawing line.

- src/Tools/Pencil.gd
- src/Tools/Pencil.tscn
Overwrite color instead of blending it.
Fixes #278
> Add overwrite option to pencil.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
These templates should ensure people provide the required information when reporting issues.
> Add issue templates for easier issue reporting

- project.godot
- src/Autoload/Export.gd
- src/Autoload/OpenSave.gd
- src/Main.gd
- src/UI/Dialogs/ExportDialog.gd
- src/UI/TopMenuContainer.gd
Split export code from export dialog to Export.gd autoload (separate gui and functional code).
Clean access to child nodes of export dialog.
Preparation for replacement of godot-gifexporter with godot-gdgifexporter by jegor377
https://github.com/jegor377/godot-gdgifexporter
> Refactor export dialog

- src/Classes/ImageEffect.gd
- src/UI/Dialogs/ImageEffects/DesaturateDialog.gd
- src/UI/Dialogs/ImageEffects/FlipImageDialog.gd
- src/UI/Dialogs/ImageEffects/HSVDialog.gd
- src/UI/Dialogs/ImageEffects/InvertColorsDialog.gd
- src/UI/Dialogs/ImageEffects/OutlineDialog.gd
> Affect area now affects the previews.

- Translations/Translations.pot
- src/Autoload/Global.gd
- src/Preferences/PreferencesDialog.gd
- src/Preferences/PreferencesDialog.tscn
- src/UI/Canvas/TileMode.gd
You can change the opacity of the surrounded tiles in tile mode.
You can change the opacity in the preference dialog under the subitem Canvas/transparency
**Overloaded Edit:** Closes #358
> Add feature request #358

- Translations/Translations.pot
- src/Autoload/Global.gd
- src/Autoload/OpenSave.gd
- src/Main.gd
- src/UI/TopMenuContainer.gd
> Add feature request #276

- src/UI/Timeline/AnimationTimeline.tscn
If someone need to look at only the past they can do that and if someone has to look only into the future this would be needed
> The minimum no of onion skin to the future and past is set to 0(Default)

- src/Main.gd
Cpu Usage is now 1% while in Idle.
Needs some testing for usability tough, set for v0.8.3/0.9.
> Improve Cpu Usage while in Idle

- src/UI/Timeline/FrameTagDialog.tscn
> Allow greater values than 100 for ToSpinBox

- src/UI/Timeline/AnimationTimeline.gd
> Select new layer after adding it

- Translations/Translations.pot
- project.godot
- src/Autoload/Global.gd
- src/Classes/Project.gd
- src/Preferences/PreferencesDialog.gd
- src/Preferences/PreferencesDialog.tscn
- src/UI/Canvas/CameraMovement.gd
- src/UI/Canvas/Canvas.gd
- src/UI/Canvas/Canvas.tscn
- src/UI/Canvas/Grid.gd
- src/UI/Canvas/PixelGrid.gd
- src/UI/Canvas/TileMode.gd
- src/UI/TopMenuContainer.gd
- src/UI/TransparentChecker.gd
Fixes #426 (implemenetation of the solution I suggested in there).
- Draw Grid only over the Canvas (when in tiling mode).
- Added PixelGrid.
- Pixel Grid is shown only when it's enabled and camera is zoomed close enough.
- Settings (to distinguish between Grid and PixelGrid default grid_width, grid_height settings are changed):
- Default values might need changing.
- Now both Grid and PixelGrid are drawn above (after) TileMode. Grid is drawn above (after) PixelGrid.
<details>
<summary>Show images</summary>
**Previous look:** see #426.
**Current look:** (both Grid and PixelGrid are enabled everywhere)
</details>
> Draw Grid only over Canvas. Added PixelGrid.

- Translations/Translations.pot
- src/Autoload/Global.gd
- src/Classes/Project.gd
- src/Preferences/PreferencesDialog.gd
- src/Preferences/PreferencesDialog.tscn
- src/Tools/Base.gd
- src/Tools/Draw.gd
- src/UI/Canvas/Grid.gd
- src/UI/Canvas/PixelGrid.gd
- src/UI/TopMenuContainer.gd
Now it should be drawn properly in the target rect.
Settings (in pixels):
- cell's AABB size,
- offset from the canvas origin.
Few images with additional debug draw:
> Refactored isometric grid

- src/Autoload/Global.gd
- src/Autoload/Tools.gd
- src/Classes/Project.gd
- src/Preferences/HandleThemes.gd
- src/Preferences/RestoreDefaultButton.gd
- src/Tools/Draw.gd
- src/UI/Canvas/Grid.gd
- src/UI/Canvas/TileMode.gd
- src/UI/Timeline/LayerButton.gd
- src/UI/TopMenuContainer.gd
- src/UI/TransparentChecker.gd
> Renamed enums to follow recommended naming convention

- src/Autoload/DrawingAlgos.gd
- src/Autoload/Global.gd
- src/UI/TopMenuContainer.gd
Th change in these files allow me to create the Centralize function
> Var pix centralize

- src/UI/Dialogs/CreateNewImage.gd
I added a few new templates from other 8/16bit devices into the basic templates.
> Added more standart devices from 8/16Bit era

- project.godot
- src/UI/TopMenuContainer.gd
Overloaded edit: The shortcut is `Control+D`
> Add keyboard shortcut for Clear Selection

- src/UI/Timeline/AnimationTimeline.tscn
> Fix onion skinning dialog sizes

- src/Autoload/DrawingAlgos.gd
I needed to add the data type to project for the scripts to compile. Pardon any mistakes, I'm still working through contributing guidelines.
> DrawingAlgos Explicit Project DataType

- .github/workflows/dev-desktop-builds.yml
Added readme for macOS users that shows them how to clear `com.apple.quarantine` attribute from app in order for it to run normally.
> Gatekeeper readme

- src/Autoload/OpenSave.gd
- src/UI/Dialogs/PreviewDialog.gd
- src/UI/Dialogs/PreviewDialog.tscn
1. Drastically changed the "Spritesheet layer" function and removed its dependence on other functions, hence reducing the amount of undos (i hope didn't break anything though)
2. "Start frame" can now be as high as you want.
3. a minor UI fix regarding "PreviewDialog.tscn"
> Spritesheet layer improvements

- src/Classes/ShaderImageEffect.gd
I found a nice little hack that should hopefully fix #615 without needing to create separate shaders
> Shader alpha fix

- src/Autoload/Global.gd
- src/Shaders/UITransparency.gdshader
- src/UI/Dialogs/WindowOpacityDialog.gd
- src/UI/UI.gd
- src/UI/UI.tscn
My attempt to make a Shader based "Alternate transparent background" **Alternative**
> Transparency fixes

- src/UI/Timeline/FrameTagDialog.gd
This pull contains:
1. Popup of "add tag" and "edit tag" dialogs at more related locations instead of dead center.
2. Start and end points of tag are now automatically determined by selected cels.
https://user-images.githubusercontent.com/77773850/151801892-bf345e1f-feee-411d-833a-27e5f82316b6.mp4
> Some Popup changes and added Self Awareness ;)

- src/Preferences/HandleExtensions.gd
A simple id system for extensions using the benefit of groups. it would suffice till a more advanced system is planned/implemented
> A simple id for extensions

- src/Shaders/DropShadow.tres
- src/UI/Dialogs/ImageEffects/DropShadowDialog.gd
- src/UI/Dialogs/ImageEffects/DropShadowDialog.tscn
- src/UI/Dialogs/ImageEffects/ImageEffects.tscn
- src/UI/TopMenuContainer.gd
This will add a new shader-based drop shadow effect
https://user-images.githubusercontent.com/54466934/164895009-ff0e05d6-e0da-47e0-9c47-54740a1ba95e.mp4
> Add Drop Shadow

- src/Preferences/HandleExtensions.gd
Added crash protection to `_add_extension(file_name: String)`
> Handle extension improvements

- src/Autoload/Export.gd
- src/Classes/ImageEffect.gd
- src/UI/Dialogs/ImageEffects/ShaderEffect.gd
When Pixelorama timeline and effects were upgraded to use selected cels, the preview display was not
this aims to upgrade that as well for better visualization
https://user-images.githubusercontent.com/77773850/180611382-525f81f2-97e0-4c87-b544-e9f69fc33a18.mp4
> Upgrade current_cel to selected_cel for Preview Display

- src/UI/Dialogs/ImageEffects/RotateImage.gd
- src/UI/Dialogs/ImageEffects/RotateImage.tscn
The Pivot will now remember it's last position
Algorithms are also re-arranged according to their speed (shader is the new default)
https://user-images.githubusercontent.com/77773850/180655267-ddaa8a71-2895-47c7-9742-a762a96ce530.mp4
> Pivot remembering and algorithm re-arrangement

- src/Classes/Drawers.gd
- src/Tools/Bucket.gd
i noticed that some of the colors drawn when selected from palette was slightly wrong (about 1px difference in either R or G or B values)
this pull attempts to fix this issue
> Fix (slightly) wrong color being drawn when selected from palette

- src/UI/Dialogs/TileModeOffsetsDialog.gd
- src/UI/Dialogs/TileModeOffsetsDialog.tscn
Load tilemask from current frame instead of selecting from FileDialog
> Change tilemask loading

- src/UI/Dialogs/WindowOpacityDialog.gd
Only make the Tabcontainer **With** the "Main Canvas" change its modulation
> Make changing window transparency only affect the main canvas' transparency

- src/Autoload/OpenSave.gd
- src/Classes/BaseCel.gd
- src/Classes/BaseLayer.gd
- src/Classes/Project.gd
- src/UI/Timeline/AnimationTimeline.gd
- src/UI/Timeline/CelButton.gd
- src/UI/Timeline/PixelCelButton.tscn
- Changed link sets from an Array to a Dictionary with { "cels": Array, "hue": float }
- Hue is calculated by finding the largest gap in hue from the layer's current link sets
> Keep colors on cel link sets

- src/UI/Timeline/AnimationTimeline.gd
New layer adding system
https://user-images.githubusercontent.com/77773850/196207143-e4ff866c-f11e-4b7a-9c13-6d31e8e53837.mp4
https://user-images.githubusercontent.com/77773850/196207177-d204399d-3fb3-4fd6-8a42-980ef1a6a74c.mp4
> Change layer adding behavior

- project.godot
- src/Autoload/ExtensionsAPI.gd
- src/Preferences/HandleExtensions.gd
This Pull adds Class System to the ExtensionApi
The Classes are:
1. GeneralAPI
2. MenuAPI
3. DialogAPI
4. ThemeApi
5. ToolAPI
6. ProjectAPI
> Added Class System to ExtensionsAPI

- src/Tools/Draw.gd
- src/Tools/SelectionTools/PaintSelect.gd
- src/UI/Buttons/BrushButton.gd
- src/UI/Buttons/BrushButton.tscn
- src/UI/Buttons/BrushesPopup.gd
- src/UI/Buttons/BrushesPopup.tscn
The old popup got a new UI upgrade:
Old:
**Maintainer edit**: Added new screenshot
New:
> Upgrade the look of the brushes popup

- src/UI/ColorPickers/ColorPickers.gd
- src/UI/ColorPickers/ColorPickers.tscn
Ported the Average Color Extension to Pixelorama Core
https://user-images.githubusercontent.com/77773850/219611103-94368e82-3c9d-491d-9fd7-b2a3ed9846a4.mp4
> Added color Averaging

- src/UI/Canvas/CanvasPreview.gd
- src/UI/Canvas/CanvasPreview.tscn
- src/UI/CanvasPreviewContainer/CanvasPreviewContainer.gd
- src/UI/CanvasPreviewContainer/CanvasPreviewContainer.tscn
even though pixelorama is designed to make sprite-sheets frame by frame instead of all in one frame
BUT...
still many still make entire sprite-sheets on a single frame/image (and complain about animating afterwards LOL)
This will now be possible
https://user-images.githubusercontent.com/77773850/225286066-b24bf367-435f-4719-a095-4bb2f32d6ac7.mp4
> Spritesheet Animation Canvas Preview

- src/Tools/Draw.gd
- src/Tools/Eraser.gd
- src/Tools/LineTool.gd
- src/Tools/Pencil.gd
- src/Tools/SelectionTools/EllipseSelect.gd
- src/Tools/SelectionTools/PolygonSelect.gd
- src/Tools/Shading.gd
- src/Tools/ShapeDrawer.gd
- src/UI/Canvas/Selection.gd
> [Targeted for 0.11.0][Bug FIX] Mirror preview fix

- src/UI/Timeline/AnimationTimeline.gd
fixed some tag bugs
https://github.com/Orama-Interactive/Pixelorama/assets/77773850/14ae70b7-0f6e-4826-a073-94d7403af6f3
> [Targeted for 0.11.0][Bug FIX] fix tag scroll bugs

- src/Autoload/ExtensionsAPI.gd
- `clear_selection()`
- `select_all()`
- `select_rect(select_rect: Rect2, operation := 0)`
- `move_selection(destination: Vector2, with_content := true, transform_standby := false)`
- `resize_selection(new_size: Vector2, with_content := true, transform_standby := false)`
- `invert()`
- `make_brush()`
- `copy()`
- `paste()`
- `delete_content()`
- `new_project(frames := [], name := tr("untitled"), size := Vector2(64, 64), fill_color := Color.transparent)`
- `switch_to(project: Project)`
- `add_new_frame(after_frame: int)`
- `add_new_layer(above_layer: int, name := "", type := Global.LayerTypes.PIXEL)`
> [ExtensionsAPI] New SelectionAPI and more project methods

- src/UI/Canvas/CameraMovement.gd
1. Do nothing further if zoom margin is infinite
2. Fit to Frame now obeys integer zoom
> Fix a bug in integer zoom

- src/UI/Recorder/Recorder.gd
fix recorder dir create function
> fix: Recorder directory create

- src/Autoload/Global.gd
- src/Tools/Draw.gd
backport of https://github.com/Orama-Interactive/Pixelorama/commit/331c46c8eeed694b724dc0f18dcf56411654d049
> [0.x] Fix undo/redo history not working when the tool changes 

- src/Autoload/Palettes.gd
- src/Palette/EditPaletteDialog.gd
- src/Palette/EditPaletteDialog.tscn
- src/Palette/PalettePanel.gd
> [0.x] Allow user to move Palettes to Trash/Recycle Bin instead of deleting them permanently 

- src/Autoload/OpenSave.gd
- src/Main.gd
> [0.x] If "Save & Exit" is pressed while quitting, don't close the software if the project failed to save

- src/Autoload/ExtensionsApi.gd
also fixed 2 functions of signal api using old (target, method) arguments instead of callable
> fixed some documentation typos

- src/Autoload/ExtensionsApi.gd
Plus some ProjectAPI revisions
> Added a way to select cels through API using select_cels()

- src/Autoload/ExtensionsApi.gd
- src/UI/Canvas/Selection.gd
Plus some minor SelectionAPI revision
> Exposed get_enclosed_image() to API

- src/UI/Timeline/AnimationTimeline.gd
- src/UI/Timeline/AnimationTimeline.tscn
- src/UI/Timeline/PasteTagPopup.gd
1.x version of #941
https://github.com/Orama-Interactive/Pixelorama/assets/77773850/b2ba8e83-cf70-48ea-9281-0536646c8c9e
Other fixes
- Fixed PasteTagPopup dialog not opening
- Fixed tag created immediately after starting pixelorama not placed correctly
> Make cloned frames only select a cel if it's coresponding original cel was selected as well

- src/Tools/3DTools/3DShapeEdit.tscn
Change the menu button to flat to indicate that it is a button that you can press and not a label.
> Make the "Add Object" button more obvious that it is a button.

- src/UI/Dialogs/ImageEffects/RotateImage.gd
Fixed the dragging of pivot gizmo in rotation dialog
https://github.com/Orama-Interactive/Pixelorama/assets/77773850/0356c912-4cf8-4f69-8f86-8c0fb7b344ec
> Fixed rotation pivot gizmo

- src/UI/Dialogs/ImageEffects/RotateImage.gd
0.x version of #976
https://github.com/Orama-Interactive/Pixelorama/assets/77773850/0356c912-4cf8-4f69-8f86-8c0fb7b344ec
> [0.x] Fixed rotation pivot gizmo

- src/Classes/ImageEffect.gd
- src/UI/Dialogs/ImageEffects/ImageEffectParent.tscn
- src/UI/Dialogs/ImageEffects/RotateImage.gd
- src/UI/Dialogs/ImageEffects/RotateImage.tscn
live/delayed preview now works with all effects, to allow this feature, simply change the visibility of `LiveSettings` node in the target effect dialog.
> Moved live preview code to ImageEffect Dialog

- src/Main.gd
Experimental refactor of the CLI
> Experimental refactor of the CLI

- src/UI/UI.tscn
> Fix ruler text not getting clipped

- src/UI/PerspectiveEditor/PerspectiveEditor.gd
- src/UI/PerspectiveEditor/PerspectiveEditor.tscn
- src/UI/PerspectiveEditor/PerspectiveLine.gd
- src/UI/PerspectiveEditor/VanishingPoint.gd
- removed some garbage code.
- made tracker toggle obey the variable in the script (on startup).
- Changed type of Perspective editor from `Control` to `PanelContainer` to avoid some issues with dockable container
> Fixes to perspective editor

- src/UI/ExtensionExplorer/Entry/ExtensionEntry.gd
- src/UI/ExtensionExplorer/Entry/ExtensionEntry.tscn
- src/UI/ExtensionExplorer/Store.gd
- fix wrong texture flag of large preview
- add fail safe if extension in version in repo file is read as a string
- add failsafe if the string is not a link
> fix some things in ExtensionExplorer

- src/UI/ReferenceImages/ReferencesPanel.tscn
> Add more info to references pannel

- src/Shaders/BlendLayers.gdshader
- src/UI/Dialogs/ImageEffects/OffsetImage.gd
https://github.com/user-attachments/assets/8761cb47-84d0-4dba-b313-57a1fb457a34
> Make clipping masks work with Move tool and offset image dialog

- README.md
Remove empty hypertext from between badges.
> Fix awkward spaces between badges

- src/UI/Canvas/Canvas.tscn
- src/UI/Canvas/OnionSkinning.gd
- src/UI/Timeline/AnimationTimeline.gd
- src/UI/Timeline/AnimationTimeline.tscn
title
https://github.com/user-attachments/assets/c0da6e3c-b893-4683-8871-ea6af5039033
There's no permanent config saving yet. I need to figure out how config saving works.
> Add onion skinning opacity adjustment

- src/Autoload/ExtensionsApi.gd
ValueSliders V2 and V3 methods will now instanciate scenes.
removed typos and improved docs
> Fix typos and stuff in ExtensionsApi

- src/Autoload/Global.gd
- src/Classes/ResourceProject.gd
- src/Classes/ShaderLoader.gd
- src/UI/TopMenuContainer/TopMenuContainer.gd
This will open the texture as a new project, saving that project won't save it locally but instead update the texture.
https://github.com/user-attachments/assets/e2e0b128-b12a-4f1e-b551-6d20fe46d668
[Files.zip](https://github.com/user-attachments/files/16827528/Files.zip)
> Added a way to modify shader textures

- src/Tools/DesignTools/Shading.gd
- src/Tools/DesignTools/Shading.tscn
This pr adds a color replace shading mode similar to aseprite
https://www.youtube.com/shorts/ty3qI4v5M0Y
https://github.com/user-attachments/assets/d6de1136-dd51-4c9b-a8e2-2afee5925a05
> ColorReplace Shading Mode

- Translations/Translations.pot
- src/Autoload/Global.gd
- src/UI/TopMenuContainer/TopMenuContainer.gd
As it is a more accurate description of what it does
> Renamed the selection "tile mode" to "wrap strokes"

- src/UI/ExtensionExplorer/Store.gd
- src/UI/ExtensionExplorer/Store.tscn
Some times when an extension turns out to be faulty/outdated this will allow users to report it, so that they are disabled in repository and their Authors notified of updating them.
> Added a way for users to report faulty extensions

- src/UI/Timeline/FrameScrollContainer.gd
See Discussion for context: https://github.com/Orama-Interactive/Pixelorama/discussions/1218#discussioncomment-12874086
> Fixed Frames panel not scrolling with InputEventPanGesture and Two-Finger scroll.

- src/UI/Canvas/Selection.gd
- src/UI/Canvas/TransformationHandles.gd
https://github.com/user-attachments/assets/24857412-2a71-4fdf-bd63-98dad0bd7c9b
https://github.com/user-attachments/assets/207b99b5-93c8-4aa5-bbe9-2a39389459ea
> Fix rotation issue with selections that are initially non rectangular

- src/Autoload/ExtensionsApi.gd
- src/Classes/ResourceProject.gd
- src/Classes/ShaderLoader.gd
- src/UI/TilesPanel.gd
- [Fix errors appearing when signal is already connected or disconnected](https://github.com/Orama-Interactive/Pixelorama/commit/b5ca488f4feb15c7b54ced3f1eff570ca4720799)
- Added docs to `ResourceProject`
- Added `get_frame_image()` to the ResourceProject.
Status: Ready for review
> Allow creating ResourceProjects through ExtensionsApi
