Scripts/Main.gd
This prevents UI elements from collapsing when resizing the window.
=> Define a minimum window size when supported

Main.tscn
This also makes it possible to load JPEG images if they have a `.jpeg` extension.
See also https://github.com/RodZill4/godot-procedural-textures/pull/35.
We should update the README as well once a new release is made :slightly_smiling_face:
=> Add support for loading additional image formats

Main.tscn
This makes use of Godot's SVG importer to load SVGs and rasterize them.
Not sure how useful this will be in a pixel art context, but I guess it doesn't hurt to expose it.
See also https://github.com/RodZill4/godot-procedural-textures/pull/49.
=> Add support for importing SVG images

Scripts/Main.gd, project.godot
This makes it possible to make the window fullscreen without using external tools.
=> Implement fullscreen toggle by pressing F11 or Alt + Enter

Scripts/Main.gd
This makes it more convenient to use Pixelorama, especially when using multiple monitors.
The associated cache configuration file could be reused in the future to store other kinds of "semi-persistent" data.
=> Remember the window position and size across restarts

Main.tscn, Scripts/CameraMovement.gd, Scripts/Canvas.gd
- Display zoom as a percentage, to be more in line with other 2D editing applications.
- Increase spacing between labels.
- Use the Unicode multiplication sign.
=> Improve the status bar display

Scripts/Main.gd
This also removes the version number from the window title, as it can be seen in the About dialog.
=> Display the name of the currently open file in the window title

Scripts/Canvas.gd, Scripts/SelectionRectangle.gd
Made it so the line tool works like how it does in GIMP. This is how I personally prefer the line tool, and I'm making this pull request in case it would be preferred by others as well.
Now, instead of holding shift before drawing, you hold shift at any time after you draw and it will show the line. From here it works like normal, where you click and it will draw in the line. The position the line is drawn from is updated every time you draw.
I also made it so the line is invisible while dragging a selection.
NOTE: I am not too familiar with the undo and redo system. So this version of the line tool currently does not revert to being drawn from previous positions when undoing.
=> Changed line tool so it activates by pressing shift after last draw

Scripts/Main.gd
This improves user experience a bit when quitting Pixelorama, especially on slower hardware.
=> Darken the UI when exiting the application

Main.tscn, Translations/#Translations.csv
In a language selection menu, languge names should be written in the target language so that they can be easily understood by those speaking the language.
This also removes the need for individual translations to supply their own strings for every language name.
=> Write each language name in the target language

Scripts/Main.gd
Follow-up to #69.
`KEY_MASK_CMD` is automatically remapped by Godot to `KEY_MASK_CTRL` or `KEY_MASK_META` depending on the OS.
=> Simplify the Command key mask binding

Scripts/Main.gd
Straight Line Tool was triggered when using _Ctrl + Shift + Z_
Now the shortcut for Redo is _Ctrl + Y_
"Show Guides" shortcut now is _Ctrl + F_
=> Change Redo shortcut

Scripts/Canvas.gd
=> Don't call `update()` in the canvas on non-mouse input events

project.godot
This results in slightly increased performance and decreased CPU/GPU usage.
This also prevents the "Directional shadow buffer status invalid" error message from appearing in the console output when using a very old graphics card.
=> Use the `2D` framebuffer allocation

Main.tscn, Scripts/Canvas.gd, Scripts/Global.gd, Scripts/Main.gd, Translations/Translations.pot, Translations/de.po, Translations/el.po, Translations/en.po, Translations/fr.po, Translations/it.po, Translations/pl.po, Translations/pt_BR.po, Translations/ru.po, Translations/zh_TW.po
Fixes #122 
implemented using checkboxes  in the the left and right tool options panels
translations are done using google translate, so they should be checked by translators
=> added option to hide tool icons next to cursor

Scripts/Main.gd
When the window adjusts its size when the program it's launched, the splash screen can be off-centered. This commit delays the popup to insure it will be centered.
=> Delay the splash screen popup so it shows properly centered

Scripts/Global.gd, Scripts/Main.gd
If you're not doing any animations and just working on a isolated sprite, having it laying around is pointlessly consuming space. So here's a option to hide it.
=> Add option to hide the animation timeline

Main.tscn
Otherwise, their tooltips won't appear.
=> Make labels with tooltips have their mouse filtering set to "pass"

Scripts/Dialogs/OutlineDialog.gd, Scripts/Dialogs/PreferencesDialog.gd, Scripts/Main.gd, Scripts/Palette/EditPalettePopup.gd
As their presets aren't saved, and for the canvas itself there's the palette system for that, they being visible is mostly pointless and creates noise.
Note that the "Add" button will still be visible due to a bug in Godot itself. It will be fixed with https://github.com/godotengine/godot/pull/36235 in a later release.
=> Hide presets in ColorPickers

Scripts/Main.gd
It's really annoying having to set the save path even after opening an existing project, so opening one now sets the save and export paths automatically.
=> Make opening a project set the save path

Main.tscn, Scripts/Import.gd, Scripts/Palette/Palette.gd, Scripts/Palette/PaletteContainer.gd
Adds ability to import a palette from a PNG file. Some palettes are distributed as PNG files with each color spanning exactly one pixel. Or it can be used to "scan" any image and get it's color palette.
=> Add palette import from a PNG file

Main.tscn, Scripts/Main.gd
Temporary fix for #109 (Till tabs are implemented in v0.8)
=> Add WarningDialog for unsaved Image before creating a new Image

Prefabs/Dialogs/PreferencesDialog.tscn, Scripts/Dialogs/PreferencesDialog.gd, Scripts/Main.gd, Translations/Translations.pot, project.godot
Adds support for changing of shortcuts for main tools. Custom preset stores changes to `cache.ini` file so they get reloaded when Pixelorama starts. Default preset cannot be changed.
=> Add tools shortcuts binding to preferences

Scripts/Dialogs/CreateNewImage.gd, Scripts/Dialogs/ImportSprites.gd, Scripts/Global.gd, Scripts/Main.gd, Scripts/OpenSave.gd, project.godot
I compared all compression algorithms that Godot offers (and included no compression results for comparison). For testing I created a file with 10 layers, 10 frames, each 1024x1024 pixels.
Save/Open times are in seconds measured on an NVMe drive. These times could be up to 10 times slower on a spinning hard drive but I hope that nobody will seriously try to create 1024x1024 pixel art...
||SAVE|OPEN|SIZE|
|---|---|---|---|
|RAW|0.5|0.7|400MB|
|DEFLATE|5.4|2.8|2.9MB|
|FASTLZ|2.7|2.2|5.8MB|
|GZIP|5.9|3|4.1MB|
|ZSTD| 2.5|1.9|2.2MB|
ZSTD came out on top with the best times and the best size reduction of *mere* **99.45%**. All hail our Facebook overlords!
=> Move open/save functions to a separate file and clean up. Add ZSTD compression.

Main.tscn, Scripts/Canvas.gd, Scripts/Drawers.gd, Scripts/Global.gd, Scripts/Main.gd
Added a pixel perfect mode for the pencil and similar brush-like tools
See issue: https://github.com/Orama-Interactive/Pixelorama/issues/192
Unrelated question: I see that you have nice variable names and the code is quite readable. Still, I feel that some methods are too long and there is a lot of repetition. Would you accept refactor-only pull requests?
=> Pixel Perfect mode for brush, eraser and lighten/darken

Translations/Translations.pot, src/UI/Dialogs/ExportDialog.gd, src/UI/Dialogs/ExportDialog.tscn
This lets people export **a single tag** or **all frames** in spritesheet export tab:
In the future, I want to work on this more to also carry this over to Animation as well and also the `Create new directory for each frame tag` over to the Spritesheet export.
=> Added selective animation tag export for Spritesheets

src/Main.gd
The latest Pixelorama versions require Godot 3.2 to run.
=> Remove fallback for `OS.min_window_size` now that Godot 3.2 is out

src/Autoload/Global.gd, src/Autoload/OpenSave.gd, src/Preferences/HandleLanguages.gd, src/Preferences/HandleThemes.gd, src/Preferences/PreferencesDialog.gd, src/Preferences/PreferencesDialog.tscn
Using a table to auto set/get prop in global, config key and connect signal.
There are some global prop and config key is not same name in old code. The config key now is force to use the name of the global prop.
Change the tree in left side to item list, it is no need to use tree.
The autosave config value is move from OpenSave to Global because using auto code.
=> Refactoring perferences dialog

src/UI/ColorAndToolOptions.tscn
I personally think they look better, and less distracting when switching tools.
=> Set tool options containers' size flags to "Fill"

project.godot
For access to VisualServer singleton from a separate thread in GDScript
=> Enable multi-threaded rendering

addons/README.md, addons/gdgifexporter/LICENSE, addons/gdgifexporter/converter.gd, addons/gdgifexporter/gif-lzw/LICENSE, addons/gdgifexporter/gif-lzw/lsbbitpacker.gd, addons/gdgifexporter/gif-lzw/lsbbitunpacker.gd, addons/gdgifexporter/gif-lzw/lzw.gd, addons/gdgifexporter/gifexporter.gd, addons/gdgifexporter/little_endian.gd, addons/gdgifexporter/lookup_similar.shader, addons/gdgifexporter/quantization/median_cut.gd, project.godot, src/Autoload/Export.gd, src/UI/Dialogs/ExportDialog.gd, src/UI/Dialogs/ExportDialog.tscn
- Remove godot-gifexporter submodule/plugin.
- Add jegor377/godot-gdgifexporter entirely written in GDScript instead.
- Add exporting of animation frames in a separate thread and an export progress bar (so Pixelorama doesn't freeze during export).
- Remove background color option from gif export since we now support transparency - color (0,0,0,0) is used as transparent.
=> New GIF export process

src/Autoload/HTML5FileExchange.gd, src/Autoload/Import.gd, src/Palette/PaletteContainer.gd, src/Palette/PaletteImportFileDialog.tscn, src/Palette/PalettePanelContainer.tscn
Added a PAL importer to fix #307. I used a palette from Lowspec to test: [Isa's Limited Ramps](https://lospec.com/palette-list/isas-limited-ramps)
**Before palette import**
Before I imported the palette, you can see that it doesn't exist.
**Adding the accepted file formats**
**Post-import Palette**
The palette takes the file name as the palette name. Note there are 28 colors which match the number of colors in the palette. 
Let me know if I need to change anything.
=> Add PAL palette format import

src/UI/Dialogs/ExportDialog.gd, src/UI/Dialogs/ExportDialog.tscn, src/UI/Timeline/CelButton.gd, src/UI/Timeline/CelButton.tscn
I added transparent backgrounds to both the export dialog and the animation cels. Fixes #206 if there's nothing holding this issue up.
**Export Dialog**
I had to make a few changes to the node structure on the dialog, as the scroll container didn't take to kindly to me adding a child checker. Neither did the grid container. I ended up putting them in a panel and sticking the checker behind them.
Here is a preview of the new node structure.
**Animation Cels**
These were as simple as adding the child and selecting display behind parent.
=> Add transparent checker to export dialog and animation cels

src/Palette/EditPalettePopup.gd, src/Palette/EditPalettePopup.tscn, src/Palette/PaletteButton.tscn, src/Palette/PaletteContainer.gd, src/Palette/PalettePanelContainer.tscn
Also added the swatch Buttons to the same group. Fixes #308
=> Created dummyBtn which holds the ButtonGrp

project.godot, src/Main.tscn, src/SelectionRectangle.gd, src/UI/TopMenuContainer.gd
I made cut-option, it appears in the top bar the function and you can call the cut with c-x
=> Cut option

Translations/Translations.pot, src/Autoload/Export.gd, src/Autoload/Global.gd, src/Classes/Project.gd, src/Main.tscn, src/UI/Canvas/CanvasPreview.gd, src/UI/Dialogs/ExportDialog.gd, src/UI/Timeline/AnimationTimeline.gd, src/UI/Timeline/CelButton.gd, src/UI/Timeline/CelButton.tscn, src/UI/Timeline/FrameProperties.gd, src/UI/Timeline/FrameProperties.tscn
Frame properties update:
- Now at right click a cell it will popup and option of "frame properties" and entering in that popup it will open a windows, in that windows it will display the frame of the cell you clicked and also how many times that frame should last (for example 1 x means 1 time which is the standart but 6 x means it will last 6 times the time it should last, at 6 FPS per sencond that is a second complete)
- The serialize() and deserialize() function has been changed to add the list frame_duration for being able to save/unsave
- The gif exporter works with the frame_duration
- The change of frame time it register as an action so it can be undo/redo
- The translation.pot has been modified
This is my first update a little big and my first time working in an open source …
=> Frame properties

src/Autoload/Global.gd, src/Main.gd, src/Preferences/PreferencesDialog.gd, src/Preferences/PreferencesDialog.tscn, src/UI/Canvas/Canvas.gd
Hello,
On my computer Pixelorama was unusable because of tiny size of the GUI. I using Linux with a screen with HiDPI but godot does not support HiDPI for Linux.
This patch some how fix the issue with an option to set the shrink value. This values is used by godot to scale the whole application. The option is available in the configuration panel of the godot project and it can be changed in live by the application. The purpose of this patch the add an option in the Parameter>Startup section to do the job.
I see few possible issue, in particular if the value is set at a too high value and the parameter screen is not usable anymore. Otherwise it work nice.
Let me know if you want some change.
Best regards.
Overloaded edit: Closes #140
=> Implement shrink option

Translations/Translations.pot, project.godot, src/Autoload/Global.gd, src/UI/Canvas/Grid.gd, src/UI/Canvas/TileMode.gd, src/UI/TopMenuContainer.gd, src/UI/TransparentChecker.gd
I have added more tiling options like tile in x axis, y axis and both axis together.
=> Improved the tiling feature

src/UI/Canvas/CameraMovement.gd
Please look at #390 before, I explained the gestures there.
Now zooming trough panning is replaced with moving the canvas through panning.
Fixes #271(?)
=> Allow moving the canvas and zooming with the touchpad

src/Autoload/Global.gd
Note that the events in the InputMap still are like this: `ctrl + cmd + s`. Maybe you wanna change it to something like this: `ctrl + s` someday. Also thanks for the better solution!
Closes #67.
=> Change shortcut key from CTRL to CMD on OSX

src/Main.gd
Closes #401.
As you may noticed, the code below `if !event.is_echo()` is only executed when `is_echo` is true. I think this is fine, but maybe it should be done differently?
=> Use undo and redo while holding the respected shortcuts

src/UI/ToolButtons.gd
The code checks if the control key is pressed, and if it is, does not proceed to change the tool.
Fixes #406.
=> Resolve conflict with remapping shortcuts

src/UI/Canvas/TileMode.gd
Now opacity is multiplicative. Fixes #413.
=> TileMode opacity fix

src/UI/Canvas/Canvas.gd, src/UI/Canvas/Canvas.tscn, src/UI/Canvas/CurrentFrameDrawer.gd, src/UI/Canvas/TileMode.gd
Fixes #416.
- Now the current frame is drawn to a separate Viewport (with transparent background) taking into account only per layer opacity,
- tiling is drawn by drawing current frame's ViewportTexture with tile mode opacity applied (using premultiply alpha blending).
=> Fix tiling mode opacity by predrawing current frame

src/Classes/Project.gd
It's `Cel`'s property and thus it changes when `frame_changed` is called (also `layer_changed` calls `frame_changed` on its own). Fixes #419.
=> Update GUI for Cel.opacity on frame changed instead of on layer change

src/Autoload/Export.gd, src/UI/Canvas/Canvas.gd, src/UI/Canvas/Grid.gd, src/UI/Canvas/Rulers/Guide.gd, src/UI/Canvas/TileMode.gd, src/UI/Dialogs/ImageEffects/ResizeCanvas.gd, src/UI/Timeline/AnimationTimeline.gd
All of these are initialized to `Vector.ZERO` and they're never changed. Also all of these classes (`Canvas`, `Grid`, `TileMode`) extend `Node2D` and thus each of them has a `transform` and a `position` (which is for example used instead of `location` when drawing mirrored view).
=> Remove unneeded Canvas.location, Grid.location, TileMode.location

src/Tools/Draw.gd
`Draw.update_mask()` is slow and it's being called by tools (pencil etc.) every time on `draw_start()`. This PR makes it a little faster by using the fact that [Array.resize()](https://docs.godotengine.org/en/3.2/classes/class_array.html?highlight=array#class-array-method-resize) makes new elements null contrary to [PoolByteArray.resize()](https://docs.godotengine.org/en/3.2/classes/class_poolbytearray.html#class-poolbytearray-method-resize) which isn't zeroing new elements.
<details>
<summary>PoolByteArray created by passing in Array with nulls is indeed zeroed.</summary>
```
var n := 10
var a := PoolByteArray()
a.resize(n)
print(a.hex_encode())
for i in range(n):
a[i] = 0
print(a.hex_encode())
var arr := []
arr.resize(n)
print(arr)
var b := PoolByteArray(arr)
print(b.hex_encode())
``` …
=> Speedup Draw.update_mask()

src/Classes/Project.gd, src/Tools/Draw.gd, src/UI/TopMenuContainer.gd, src/UI/TransparentChecker.gd
When drawing in a tile mode `get_tile_mode_rect` is being called as many times as `_set_pixel`. This PR make tile mode rects being cached for a little speedup.
---
Example performance comparison for 128x128 canvas size and single clicks with 100x100 pencil tool:
- Before:
- After:
=> Cache tile mode rects

src/Autoload/OpenSave.gd
In `OpenSave.reload_backup_file` after the first removal with `project_paths.remove(backup_paths.find(backup))` the index returned by `backup_paths.find(backup)` will no longer point to the project path respective to that `backup`, `project_paths` and `backup_paths` arrays would be "desynchronized". This PR makes both arrays be changed properly when iterating over the backup paths (and shrinked if needed after the loop).
=> Fix potential index out of bounds error

src/UI/ColorAndToolOptions.gd
The color picker widget in HSV mode was resetting HS when you drag V to zero.
Thought about changing Tools.assign_color() to take an optional `signal_color_changed` boolean. But, I can imagine other objects connected to `Tool.color_changed` that may want dynamic updates as you use a color picker in the future. So the fix here is to temporarily disconnect `ColorAndToolOptions` from `Tool.color_changed` while the popup is active. This isolates the fix to the thing that needs fixing.
=> Fix hue and saturation getting reset when draging value slider to zero

src/Autoload/Global.gd
Fixes #493
It's debatable if it's the right choice, just using Shift, but I think it's fine.
=> Use CMD+Shift+H for showing the pixel grid on OSX

src/Tools/Shading.gd
This should fix some problems with the Saturation and Value part of the Shading Tool (NOT the Hue problems).
Left grey theme is previous build, right side is new one.
Problem 1: If you darkening value is more than the value of the color, it can end up brightening instead (I think Godot's Color class might wrap around values when setting them)
(Checked the color with the color picker to make sure it was right hue and at the value limit of 10)
Problem 2: If you darken not quite enough for that, but still too much, it will hit the value limit and ignore the darkening. Now it will just be set to the Value limit:
Problem 3: When lightening too much using Saturation, the hue could get messed up, I'm not entirely sure why this happened, but applying the same fix I did to the value part seemed …
=> Fixed issues with Shading tool Saturation and Value not always being right in Hue Shading mode

src/Tools/Shading.gd, src/Tools/Shading.tscn
- Changed hue_darken_limit from purple to blue.
- Limited the Hue Shift slider to a range of 180 so that half of it wouldn't always hit the hue shift limits.
- Fixed hue shifting issues:
- Lightening past the limit would do nothing for some colors rather than set it to the hue limit: (Left side before, right side after)
- Same happened with darkening for some colors (the red and magenta patches), while others would end up not being limited at all, instead going to incorrect hues (everywhere should have been changed purple).
- Also:
- When finally shifting the hue used fposmod to work around a Godot Color bug that made shifting the hue around the "ends" of the color wheel not always return the correct hue.
- Replaced 359.0 in code to 360.0 which fixed some instances of the hue shift being …
=> Shading Tool Hue Shift Fixes + Tweaks

src/UI/Dialogs/SplashDialog.gd, src/UI/Dialogs/SplashDialog.tscn
Two arrows are now located at the sides of the current artwork. When pressed the artwork changes to the one next in the array of artworks. The array was a dictionary before, but using it simplifies everything a lot.
Everything should be accounted for, the arrow icons change according to theme and the code checks that the array doesn't go out of bounds.
=> Add buttons for looking at different Splashscreen Artworks

Translations/Translations.pot, src/Autoload/Global.gd, src/Main.gd, src/Preferences/PreferencesDialog.gd, src/Preferences/PreferencesDialog.tscn
A new setting was added trough which the user can set how many FPS Pixelorama should have when idle.
Additionally a bug was fixed where when the user has another application as their focus and reenters Pixelorama with the mouse but not focusing it and then exiting with the mouse, the target_fps would be set to the standard.
=> Add idle fps setting

src/Shaders/Desaturate.shader
Updated desaturate shader to use perceptual luminance instead of HSV. See https://en.wikipedia.org/wiki/HSL_and_HSV#Disadvantages
Before:
After:
Thank you for considering this pull request.
Best,
Jeremy
=> Use Luminance In Desaturate Shader

.github/workflows/dev-desktop-builds.yml, .github/workflows/release.yml
This should solve the "Pixelorama is damaged" error on macOS, as suggested by https://github.com/Orama-Interactive/Pixelorama/issues/516#issuecomment-983360949.
=> Ad-hoc sign Mac builds

src/Tools/Draw.gd, src/Tools/Eraser.gd, src/Tools/LineTool.gd, src/Tools/Pencil.gd, src/Tools/Shading.gd, src/Tools/ShapeDrawer.gd
I have fixed a bug reported in [https://github.com/Orama-Interactive/Pixelorama/issues/555](url) which happens when undo is performed while drawing with pencil/eraser/shading tools.
The gif above is a bug I reproduced by following the steps described in the issue. The first line reappears if undo is performed while drawing the third line. But it can be removed by performing undo once more.
This one would be the worst case scenario. If undo is performed twice after drawing the third line, The reappeared first line cannot be removed with undo so it should be removed manually.
The simplest solution I have come up with was moving `project.undo_redo.create_action(action)` in `commit_undo()` in Draw.gd to `prepare_undo()` so undo would be disabled while drawing. Due to this change, I also have …
=> Fix drawing bug reported in issue-555

src/Autoload/Global.gd, src/Autoload/Tools.gd, src/UI/Canvas/Rulers/Guide.gd
Pan tool (**and Pan Tool alone**) is granted access to move guides without moving mouse outside canvas
=> Move Guides without moving mouse outside canvas

src/Tools/BaseTool.gd, src/Tools/Draw.gd
Should improve drawing on large size canvas significantly faster, similar to pull #554 and may solve issue #501. I would like it if @sayaks also get credited cause he was also working on the same issue 😁
=> Draw optimizer

src/UI/Canvas/Canvas.gd
In this line, a new texture is generated each time the canvas is updated it seems :
But it is mentionned in the documentation to use `void set_data(image: Image)` instead for slightly faster results, which updates the texture instead of creating a new one.
I hope that it is relevant !
Also, if it is approved, this change should be applied to everywhere it is used (except when initializing the texture)
=> Optimize canvas texture updates

src/Tools/Bucket.gd
By cutting down on some tests that were being repeated after a point had already been found to be one to be colored, I made the flood fill a bit faster again.
=> Further speed up of bucket fill

src/Tools/Bucket.gd
Separated out the larger functions to ease readability and possible future improvements.
=> Refactored bucket.gd

src/Shaders/Rotation.shader, src/UI/Dialogs/ImageEffects/RotateImage.gd
This will add a new shader based rotation mode, it's close to nearest neighbour but it uses GPU so it's much faster
https://user-images.githubusercontent.com/54466934/165759245-b01231e2-7af3-4735-96bd-c0f99ee52f5d.mp4
=> Shader based rotation

src/Shaders/DropShadow.tres, src/UI/Dialogs/ImageEffects/DropShadowDialog.gd
Currently drop shadow has issues
1. Incorrect blending because rgb blends with shadow color (as background, which is not a problem on opaque pixels)
2. Pixels on the edge are stretched
This PR will fix them.
Before:
After:
=> Fix drop shadow

src/UI/Dialogs/TileModeOffsetsDialog.gd, src/UI/Dialogs/TileModeOffsetsDialog.tscn
I forgot to implement this requested feature in #707
=> Add reset button to tile mode offsets dialog

src/Tools/SelectionTools/SelectionTool.gd
The snapping becomes weird if the "grid offset" is larger than the "grid size"
I fixed the bug by correcting lines 144 and 145 of SelectionTool.gd
(Note: i was only able to fix this for the selection code, the move tool still has this bug)
=> offset corrections

src/Tools/Move.gd
Okay, so i modified it a bit,
1) I separated the offsetting of selection snapping from the move snapping (selection offsetting is done in `_input()` while move offsetting is done in `_snap_position()`)
2) Selection (in move tool) follows proper snapping while The normal move snapping are just increments of grid_size (Cause there is no proper definition for move snapping, i mean for a selection there is a clear corner of selection that can snap to grid even when multiple frames are selected, BUT for simple move snapping the concept of corner becomes "blurry" especially when one considers multiple selected frames, so i chose simple increments for move snapping cause it seems more logical "
3) And the user is given ability to align snapping with grid-lines themselves 😉")
**Old …
=> Fixed move offsets

src/Shaders/Rotation.shader, src/UI/Dialogs/ImageEffects/RotateImage.gd, src/UI/Dialogs/ImageEffects/RotateImage.tscn
This pull will expose the pivot option in the rotation dialog thus making it **exponentially** easier to make cut-out animations
A special thanks to @AlphinAlbukhari (Elid Elid) for helping me fix it for shader rotation algorithm and help in find bugs
https://user-images.githubusercontent.com/77773850/180602856-c78aa66a-9375-42c2-a80d-d258124fc0a9.mp4
=> Expose pivot Option

src/UI/Dialogs/ImageEffects/RotateImage.gd, src/UI/Dialogs/ImageEffects/RotateImage.tscn
This pull is an attempt to make Rotate dialog UI a bit cleaner by removing the quick rotation buttons for "initial angle" cause they may not have much use anyway
=> removed initial angle quick rotation buttons

project.godot, src/Autoload/DrawingAlgos.gd, src/Autoload/Global.gd, src/Autoload/Palettes.gd, src/Classes/Project.gd, src/Classes/SelectionMap.gd, src/Shaders/ColorSelect.gdshader, src/Tools/BaseTool.gd, src/Tools/Bucket.gd, src/Tools/Draw.gd, src/Tools/SelectionTools/ColorSelect.gd, src/Tools/SelectionTools/ColorSelect.tscn, src/Tools/SelectionTools/EllipseSelect.gd, src/Tools/SelectionTools/Lasso.gd, src/Tools/SelectionTools/MagicWand.gd, src/Tools/SelectionTools/PolygonSelect.gd, src/Tools/SelectionTools/RectSelect.gd, src/Tools/SelectionTools/SelectionTool.gd, src/UI/Canvas/Selection.gd, src/UI/Dialogs/ImageEffects/DesaturateDialog.gd, src/UI/Dialogs/ImageEffects/DropShadowDialog.gd, src/UI/Dialogs/ImageEffects/FlipImageDialog.gd, src/UI/Dialogs/ImageEffects/GradientDialog.gd, src/UI/Dialogs/ImageEffects/GradientMapDialog.gd, src/UI/Dialogs/ImageEffects/HSVDialog.gd, src/UI/Dialogs/ImageEffects/InvertColorsDialog.gd, src/UI/Dialogs/ImageEffects/OutlineDialog.gd, src/UI/Dialogs/ImageEffects/RotateImage.gd
**Requires Godot 3.5 and above. Builds will most likely fail because of this and this PR will not be merged until Godot 3.5-stable is released and Pixelorama's workflows start using it.**
This PR replaces the BitMap that was used to store the selected state of the pixels with an LA8 Image. This massively improves performance, since we get rid of the slow bitmap-to-image conversion. Images were used anyway for the selection marching ants outline to be drawn, and for shaders to use them as masks.
I have also refactor the selection code by making a new `SelectionMap` class that extends Image, and moved some methods from Project.gd to the new class, therefore making the code cleaner and putting the methods to a more correct place.
A comparison of approximate common timings of full canvas …
=> Refactor the selection system to use an Image instead of a BitMap

README.md, src/Autoload/ExtensionsAPI.gd, src/Preferences/HandleThemes.gd, src/UI/Dialogs/TileModeOffsetsDialog.tscn
1. Added new `set_theme` and `find_theme_index` methods to ExtensionsAPI
2. Make **HandleThemes.gd** wait in case themes are being loaded from extensions
3. Hide the accidentally visible **TileModeOffsetsDialog.tscn**
4. update readme for Godot 3.5
=> New theme-related methods to ExtensionsAPI

src/Autoload/OpenSave.gd, src/UI/Dialogs/PreviewDialog.gd
Implements 2nd point of  #735
> Import dialog should remember the last option. I was importing separate frames of animation and I had to always re-select New frame.
=> Remember last choice in import options

src/Autoload/OpenSave.gd, src/UI/TopMenuContainer.gd
Implements the second half of #735
> These are great ideas. Another small oddity I found, is on the recent projects menu. At the moment, the list shows the most recent project at the bottom instead of the top.
1. Makes the most recent project appear at the top.
2. When you open a project already in the recent projects list if it would then be moved to the most recent spot on the list (idea by [@mrtripie](https://github.com/mrtripie))
https://user-images.githubusercontent.com/77773850/191276790-9bceefca-ad03-4f0f-aa1c-63a00706e9c4.mp4
=> Changed Recent Projects Behavior

Translations/Translations.pot, src/Autoload/OpenSave.gd, src/Classes/BaseCel.gd, src/Classes/BaseLayer.gd, src/Classes/GroupLayer.gd, src/Classes/PixelCel.gd, src/Classes/PixelLayer.gd, src/Classes/Project.gd, src/UI/Timeline/AnimationTimeline.gd, src/UI/Timeline/CelButton.gd, src/UI/Timeline/LayerButton.gd, src/UI/Timeline/PixelCelButton.tscn, src/UI/Timeline/PixelLayerButton.tscn
Implemented #719 
- New concept of a "link set":
- Layer's linked_cels array of Frames was replaced with a cel_link_sets array of array of Cels
- **Each inner array represents a "link set", allowing for a single layer to have multiple different sets of linked cels**
- The Frames were changed to Cels which makes certain things easier and others harder, but I think makes more sense
- Each Cel has a reference to its link_set array, if linked, or null if not
- The linked cel indicator on Cel Buttons is now a different hue depending on the index of the Cel's link_set inside the Layer's cel_link_sets array.
- An issue with this is that when a link sets are added/removed to cel_link_sets, other link_set's hue will change. (and when undoing and its removed/added back it will likely be a different …
=> Linked Cel Refactor and Timeline Refactor Tweaks

src/Autoload/OpenSave.gd
This fixes this error that showed up in the #698 PR when opening a pxo file (without any changes to the empty default file):
```
E 0:00:11.149   getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: nullptr
<C++ Source>  ./core/rid.h:151 @ getornull()
```
This was caused by Global.canvas.update() not being called
Also fixes the grid not being updated, and maybe other bugs.
Not sure if just using the Project.change_project() will cause other issues though
=> Fix id_map error on open_pxo_file as well as grid being wrong size

src/Tools/Move.gd, src/UI/Timeline/CelButton.gd
Fixes:
- Crash when using the move tool with a GroupCel selected, _with a PixelLayer as the current layer_
- Deleting content on a linked cel (via the cel button's right click menu, or middle clicking on it)
=> Fixed Move Tool with Group Cel Selected and Deleting Cel Content on a Linked Cel

project.godot, src/Autoload/Export.gd, src/Classes/AnimationExporters/APNGAnimationExporter.gd, src/Classes/AnimationExporters/BaseAnimationExporter.gd, src/Classes/AnimationExporters/GIFAnimationExporter.gd, src/Main.tscn, src/UI/Dialogs/ExportDialog.gd, src/UI/Dialogs/ExportDialog.tscn
This allows exporting animations in the APNG format (which doesn't have the palette or transparency limitations of GIF).
It also cleans up the internals to allow adding more animation export formats easily.
The main UI change is making the export file format selector actually usable to select file formats.
Test example of exported output:
=> APNG Exporter

project.godot, src/Autoload/Global.gd, src/Autoload/OpenSave.gd, src/Classes/Project.gd, src/Main.tscn, src/UI/Canvas/ReferenceImage.gd, src/UI/Dialogs/PreviewDialog.gd, src/UI/ReferenceImageButton.gd, src/UI/ReferenceImageButton.tscn, src/UI/ReferencesPanel.gd, src/UI/ReferencesPanel.tscn, src/UI/UI.tscn
Affects #565.
Usecase:
A friend of mine was looking for a pixel editor that was, well, not the one we've all heard of, and considers high-resolution reference images to be critical to her rotoscoping workflow.
Images:
Usage:
+ `New reference image` is a new image open type.
+ Reference images are not stored in the project file due to size reasons.
+ Reference images may be scaled and positioned in project space in a newly added panel (currently appearing as a tab of Tools, which is unfortunate)
TODO:
+ Figure out how to make it work with the UI layout
+ Anything I forgot (it appears that Pixelorama code requires changing things in a lot of places, and it's possible I forgot something)
Rationale of implementation decisions:
Layers were not used as the state of the code makes this …
=> Reference Images

Translations/Translations.pot, project.godot, src/Autoload/Export.gd, src/Classes/GroupLayer.gd, src/Classes/ImageEffect.gd, src/UI/Dialogs/ExportDialog.gd, src/UI/Dialogs/ExportDialog.tscn, src/UI/Dialogs/TileModeOffsetsDialog.gd, src/UI/Nodes/CollapsibleContainer.gd, src/UI/Nodes/CollapsibleContainer.tscn
Implements https://github.com/Orama-Interactive/Pixelorama/discussions/605#discussioncomment-4190666. Deviates from the original proposal and does not implement all of the new suggested features yet.
This PR makes the export dialog more intuitive and simpler to use by merging the "Frame" and "Animation" tabs into one. Now, all frames will be exported as multiple png files by default, with the ability to choose only to export the currently selected frame(s), thus keeping the functionality of the previous "Frame" tab and only exporting one png file, or multiples if there are more than one selected frames. To export a .gif or a .apng file, simply change the file extension.
The PR also adds some new features:
- Specific layer exporting. Choose between all visible layers, selected layers, or …
=> Export dialog UX overhaul

src/UI/Dialogs/ManageLayouts.gd, src/UI/Dialogs/ManageLayouts.tscn
Added a decorative preview to layouts, that gives you an idea of what the preview looks like
keep in mind it's only a preview and won't change the actual layout, i think the current method is more efficient (i-e create a new layout and delete the old layout)
https://user-images.githubusercontent.com/77773850/205478749-1cd98119-641f-4eba-872a-1cdeb366980b.mp4
=> Added a preview to layouts

src/UI/Canvas/ReferenceImage.gd, src/UI/ReferenceImageButton.gd, src/UI/ReferenceImageButton.tscn
Improved the Reference image panel UI
This pull includes:
1. Better alignment of Position, Scale, Opacity Sliders
2. The text of "Remove" button is Red
3. Clicking on the "Path" now opens the folder in which reference image is placed (disabled for HTML)
4. A new Image Preview
5. A new option to enable or disable filter (Filter is off by default)
6. A warning appears if the image is not found
=> Reference UI improvements

src/Tools/BaseTool.gd, src/Tools/BaseTool.tscn, src/Tools/SelectionTools/ColorSelect.gd, src/Tools/SelectionTools/EllipseSelect.gd, src/Tools/SelectionTools/Lasso.gd, src/Tools/SelectionTools/MagicWand.gd, src/Tools/SelectionTools/PaintSelect.gd, src/Tools/SelectionTools/PolygonSelect.gd, src/Tools/SelectionTools/RectSelect.gd, src/Tools/SelectionTools/SelectionTool.gd, src/Tools/SelectionTools/SelectionTool.tscn
1) Removed HSeparators from tool headers
2) Added Selection modes:
- 4 modes Default (that obeys shortcuts)
- Other 3 don't obey shortcuts and will lock a specific mode (handy when we need to do adding over and over, and so on)
https://user-images.githubusercontent.com/77773850/209374031-9d453b27-a5cc-4463-990c-4a3b7134b318.mp4
=> Selection modes

src/UI/Canvas/Rulers/HorizontalRuler.gd, src/UI/Canvas/Rulers/VerticalRuler.gd
Used `stepify()` function to restrict numbering up-to one decimal place
=> Allow floating point for Horizontal and Vertical Rulers

src/Autoload/ExtensionsAPI.gd
1. Tools are now properly Removed
2. A new `get_current_cel_info()` method
3. A new `show_error()` method. (useful for displaying messages like "Incompatible API" etc...)
=> Api Improvements

src/Preferences/HandleExtensions.gd
This will implement a new parameter called `supported_api_versions`
Note that the extension will still work without this parameter in `extension.json` but if it is included, then pixelorama will do an additional check if it's current api is present in the `supported_api_versions`
an example of extension.json containing this parameter is given below (this extension will now only work on pixelorama Api versions 1 and 2). So in case Api version 3 contains breaking changes it will simply show an error dialog instead of a BIG LOUD CRASH
```swift
{
"author": "Variable",
"description": "Test the new Api",
"display_name": "TestAPI",
"license": "MIT",
"name": "TestAPI",
"nodes": [ "Main.tscn" ],
"version": "0.1",
"supported_api_versions": [1, 2]
}
```
=> Added supported_api_versions parameter

src/Tools/Move.gd, src/UI/Canvas/Canvas.gd
At-least i managed to fix the move tool preview
=> Fix previews

src/Tools/ColorPicker.gd, src/Tools/ColorPicker.tscn, src/Tools/Draw.gd
Color Pickers will now pick the top color by default
=> Make the color picker pick any visible color on the canvas, regardless of layer

Misc/Linux/com.orama_interactive.Pixelorama.desktop, Misc/Linux/com.orama_interactive.Pixelorama.xml
Pixelorama's .desktop file now contains all the file types it can open by default (Used by DEs to provide app suggestions in context menus).
Also adds a MimeInfo file for `.pxo`. It provides context for the format and can be used by packages to register and associate the file format with the application (like flatpak)
=> Update .desktop file and add new MimeInfo

src/Tools/ColorPicker.gd, src/Tools/Draw.gd
The "Current layer" mode was able to pick-colors from a locked layer, while the "Top Color" mode was not;
this will fix that issue (i only needed to see if layer was visible or not)
=> Fix top color picking

src/UI/Canvas/OnionSkinning.gd
While using the "Move" tool, the onion skin will move it's past and future frames accordingly if they are in selected cels to give a better idea of where it will land,
(NOTE: selections will still work as it did previously i-e update onion shin after transformation is confirmed)
https://github.com/Orama-Interactive/Pixelorama/assets/77773850/e82b180b-c175-4c54-8e7c-ceada8ca1fd6
=> [Targeted for 0.11.0] Make Onion skin update live with the "Move" tool

src/UI/Timeline/AnimationTimeline.tscn
Limited value sliders of past and future frames to 10 and enabled the `allow greater` option so you can still set it to values greater than 10
=> Limit onion skinning slider max values to 10

src/UI/Dialogs/ExportDialog.gd, src/UI/Dialogs/ExportDialog.tscn
adds a message instructing user what to do in case Gif export goes wrong
=> Export Gif Message

src/Autoload/Export.gd, src/Autoload/ExtensionsAPI.gd, src/UI/Dialogs/ExportDialog.gd
Continuation of #810
A Looooong awaited feature to be added to the ExtensionsApi
You can now add custom export options using extensions. but wait!!!, there's more.... they can also contain gdnative!
The main reason why gdnative wasn't being loaded was that the libraries (the ones that end with with .so, .dll,  etc...), can't be loaded from a virtual file system (e.g .pck) so what the workaround is to simply place the libraries in a github repo and download them through HttpRequest (it can be a one-time process)
So now that i've figured out the issue and created an example extension (which was the condition in the original PR)
https://github.com/Orama-Interactive/Pixelorama/assets/77773850/1f05f564-bc06-4600-a6f9-c74b192961e2
=> [Targeted for 0.11.0] Export options to extension

src/Main.gd, src/UI/Dialogs/ExportDialog.gd, src/UI/TopMenuContainer/TopMenuContainer.gd
to "Save" (also changes to "Save & Quit" when needed) and "Export"
=> Fix Ok button Text of Save and Export Dialog

src/UI/Timeline/AnimationTimeline.gd
This causes the opacity slider to update all selected frames of the current layer rather than just the current frame.
This is useful because opacity is treated independently of cel linking, so without an option like this it's hard to work with layers you want to have one global opacity.
An example of this is if you have, say, a "noise layer" on your sprite (i.e. import noise from some other application, cut it to fit the sprite, then adjust opacity to taste). This is useful for adding a bit of texture. But combining a noise layer with animation is awkward because the opacity is per-frame, so you have to have everything setup at the start or individually adjust each layer.
=> Update opacity across selected frames

src/UI/Dialogs/ExportDialog.tscn
The LineEdit node for file name in Export Dialog seems to behave weirdly when the Align property is set to Right, as is shown in the gif:
In the picture, I pressed Backspace once per time, but at the second time, 2 charactors disappeared together with the caret.
The cause of the bug remains uncleared, but simply setting the Align property to Left solves the problem like this:
* The LineEdit for file name in Export Dialog now aligns on the left side
=> Set alignment of the LineEdit Node for file name in Export Dialog to Left

src/Tools/Draw.gd
this is the proposed changes related to #883
=> Compress image data that is memorized for undo/redo operations

project.godot, src/Autoload/ErrorManager.gd, src/Autoload/Export.gd, src/Autoload/OpenSave.gd, src/Main.tscn, src/Preferences/HandleExtensions.gd
Elaborates errors more clearly (the messages are the same as what is given in godot documentation)
=> Error elaborator

Translations/Translations.pot, src/Autoload/Palettes.gd, src/Palette/CreatePaletteDialog.tscn, src/Palette/EditPaletteDialog.gd, src/Palette/EditPaletteDialog.tscn, src/Palette/PalettePanel.gd, src/UI/ReferenceImages/ReferenceImageButton.gd, src/UI/ReferenceImages/ReferenceImageButton.tscn
Some additional changes that I thought be added to this pull request.
1. Fix deleted signal emitted wrongly
- it was written as `deleted.emit(deleted)` which did not seem to be working so i changed it to `deleted.emit()`
2. Fix create and edit palette dialog UI
- Dialog titles of `CreatePaletteDialog.tscn` and `EditPaletteDialog.tscn`
- Label Autowrap and alignment to match how they were in v0.11.2 (In `CreatePaletteDialog.tscn` and `EditPaletteDialog.tscn`)
- a minor ui change in `EditPaletteDialog.tscn` that allows comment to expand vertically
3. fix path nodes renamed to path3d by godot project converter
- `ReferenceImageButton.tscn` and `EditPaletteDialog.tscn`
=> Allow user to move Palettes to Trash/Recycle Bin instead of deleting them permanently

src/Autoload/ExtensionsAPI.gd, src/Autoload/Global.gd, src/Autoload/OpenSave.gd, src/Classes/Project.gd, src/Main.gd
Global (also accessible directly from ExtensionAPI)
- pixelorama_opened
- pixelorama_about_to_close
- project_created(Project)
Project.gd:
- serialized(Dictionary)
- about_to_deserialize(Dictionary)
OpenSave:
- project_saved
SignalsAPI now uses Callables
=> Added new signals

src/Autoload/Export.gd, src/Autoload/ExtensionsAPI.gd, src/Preferences/HandleExtensions.gd, src/UI/Dialogs/ExportDialog.gd, src/UI/Dialogs/ExportDialog.tscn
The export api is now as it was before
(well not exactly since last time i took the easy way out and just used enum as a dictionary)
so this can be considered the second iteration of the export api, a Re-Factor
this pull adds:
- fixed custom file format descriptions, not showing
- the custom exporters are given the power to display their own preview
https://github.com/Orama-Interactive/Pixelorama/assets/77773850/394a8ea7-c214-4b08-8dfa-f2488d3ca388
(The project used: [test.pxo.zip](https://github.com/Orama-Interactive/Pixelorama/files/13023334/test.pxo.zip))
Test extension (Code):
[ExportTest.zip](https://github.com/Orama-Interactive/Pixelorama/files/13023565/ExportTest.zip)
=> Re-implement the ability to add custom export formats from extensions and allow preview display

src/Classes/Cel3D.gd, src/Classes/Project.gd
3d cels should be backwards compatible now as well in case user decides to switch back to 0.x for it's lighting
=> [0.x] Fix cel3d compatibility when transferring project from 1.0 to 0.x

src/Preferences/HandleExtensions.gd, src/Preferences/PreferencesDialog.tscn
- move the faulty extension to a separate folder
- don't delete incompatible extensions (v0.11.x --> v1.0). so that they can still be used with (0.11.x)
- on uninstall ask user if they wish extension to move to bin or permanent deletion
=> Ask user if they wish to delete Extensions permanently or not

src/UI/Timeline/AnimationTimeline.gd
=> [0.x] Make cloned frames only select a cel if it's coresponding original cel was selected as well

Translations/Translations.pot, src/Autoload/OpenSave.gd, src/Classes/BaseCel.gd, src/Classes/Cel3D.gd, src/Classes/PixelCel.gd, src/Main.gd
Implements #939, solution 1. This PR makes .pxo files be .zip files in disguise, i.e., changing the extension from pxo to zip actually lets you open the file in a archive manager and view its content. Breaks forward compatibility with 0.x, meaning that pxo files exported with 1.x will not be able to be imported in 0.x. The opposite is true, however, pxos made with 0.x can be imported in 1.x.
Also provides an option to include the final blended images of each layer for easier importing by other software, and exporting with CLI, when it gets implemented. The option is disabled by default so save disk space and to reduce saving time.
The main reasons I think this solution is better than going with SQLite is that Godot already supports zip packing and reading, while SQLite would require a …
=> Change the file format of pxo to be a ZIP

src/UI/Dialogs/ImageEffects/RotateImage.gd, src/UI/PerspectiveEditor/PerspectiveLine.gd, src/UI/PerspectiveEditor/VanishingPoint.gd
These issues are not present in 0.x
1. [Rotate Image] Set `width` = -1 (default value), so the arc line will automatically adjust itself to remain thin (in 0.x this behavior was achieved at  `width` = 1 or `0.5`)
2. [Perspective lines] A small delay was needed for Global.camera.zoom to have correct value (bug was noticed when project containing perspective lines was `loaded at startup`)
3. [Perspective vanishing point] Changed a typo `Global.camera.zoom.x * 8` --> `8 / Global.camera.zoom.x` (it was probably missed during project conversion)
=> Fixed some issues with perspective lines and removed unneeded code from the rotate image dialog

src/Autoload/Export.gd, src/Autoload/Global.gd, src/Preferences/PreferencesDialog.gd, src/Preferences/PreferencesDialog.tscn, src/UI/Dialogs/ExportDialog.gd
This PR implements the ability to export projects to video formats (mp4, avi, ogv, mkv & webm) using FFMPEG. **FFMPEG itself is NOT bundled in Pixelorama, and thus needs to be downloaded as a stand-alone software. Then, you need to insert the file path of FFMPEG's binary in Pixelorama's preferences.** ~~I have only tested it on Linux so far.~~ EDIT: Should also work on Windows. In the future we could look into bundling it with GDExtension, if the licenses are compatible. Otherwise, I suppose it could be in the form of an extension.
It works by saving all of the frames as png files in a temp folder, then FFMPEG is called to convert the png files into a video, taking into account the project's fps and the delay of each individual frame. Then, the temporary png files are being deleted. …
=> Video exporting by calling FFMPEG externally

src/Autoload/Palettes.gd
- Fixes Columns field being ignored when imported.
- `_fill_imported_palette_with_colors` is modified to accept an optional width parameter, which defaults to Palette.DEFAULT_WIDTH instead of a hard-coded 8.
- A maximum of width of 16384 is enforced to mitigate maliciously large values.
=> Implement Columns field of imported .gpl palettes.

src/Palette/EditPaletteDialog.gd, src/Preferences/ExtensionsPreferences.gd, src/UI/Timeline/CelButton.gd, src/UI/TopMenuContainer/TopMenuContainer.gd
Currently, a few buttons and labels in Pixelorama aren't getting updated when changing languages, they just remain at the language the program started up with or only update when changing projects.
For the example below: I set the language to Greek, restarted the program and then switched the language back to English.
Other than these buttons in the File menu, there are different places where this also happens (see the changes included).
Here's how this PR fixes it:
- For the simple strings, all that was needed to do was remove the `tr()` when setting them up as they need to stay in English for `TranslationServer` to work with them.
- For the strings that have formatting (that is, strings that can only be partially translated, like the Save button above which has the project's name in …
=> Fix certain strings not updating when language changes

Translations/Translations.pot, src/UI/ColorPickers/ColorPicker.gd, src/UI/Dialogs/ExportDialog.tscn, src/UI/ReferenceImages/ReferencesPanel.tscn
Adds many missing strings to `Translations.pot` and fixes a few ones that were broken either because of missing periods, differences in capitalization or because of trailing newlines (the latter seems to get automatically trimmed in tooltips during runtime, better watch out for those in the future).
I don't know if anything is lost when an existing source string is changed in crowdin, so I mostly updated the broken strings in Pixelorama instead where I could in order to match the ones in the POT.
=> Add missing translation strings and fix broken ones

src/Autoload/Global.gd, src/Preferences/PreferencesDialog.gd, src/Preferences/PreferencesDialog.tscn
Someone reported problems with lagging UI on discord. It looks like it is Godots low processor usage mode not working correctly, so i thought we could add a setting for disabling it.
=> Add setting for Godots low processor usage mode

src/UI/Canvas/Grid.gd
Fixes a regression from #900 which changed some floating point calculations into integers.
Example broken setup|Before<br>(v1.0.1-stable)|After<br>(this PR)
-|-|-
=> Fix isometric grid calculations using ints instead of floats

.gitmodules
> https://github.com/novhack/godot-gifexporter.git
Is for Godot 3 and seems outdated. I haven't found any reference to it.
=> .gitmodules: remove

src/UI/Buttons/BrushesPopup.gd
This should fix issue #958 (reset custom brush when switch another tool) by removing the childs safely from BrushPopup when project data is cleared.
=> Fix Orama-Interactive#958 (reset custom brush when switch another tool)

Translations/Translations.pot, src/Autoload/DrawingAlgos.gd, src/Classes/Layers/BaseLayer.gd, src/Classes/Layers/GroupLayer.gd, src/Classes/Project.gd, src/Shaders/BlendLayers.gdshader, src/UI/Canvas/Canvas.gd, src/UI/Canvas/CanvasPreview.gd, src/UI/Dialogs/ImageEffects/OffsetImage.gd, src/UI/Timeline/AnimationTimeline.gd, src/UI/Timeline/CelProperties.gd, src/UI/Timeline/LayerButton.gd, src/UI/Timeline/LayerProperties.gd
Layers that belong to the same group are now being blended together into a single texture, which represents the entire group. Layers outside the group are not affecting the group's blended texture. This has several advantages:
- Group layers can have their own blend modes.
- Group layers can both act as a clipping mask and be used by a clipping mask.
- Group layers and cels now have their own opacity.
- Group layer effects are no longer being applied recursively to each of its children, but instead they are being applied once in the final blended texture. This allows us to use some modern non-destructive techniques, such as HD Index Painting with dithering support. https://www.youtube.com/watch?v=7Q36EyvaYG8
- A new "pass through" blending mode has been added that is only available for …
=> Implement support for group layer blending

src/UI/Timeline/AnimationTimeline.gd, src/UI/Timeline/AnimationTimeline.tscn, src/UI/Timeline/LayerButton.gd
Add global layer buttons to change visibility, lock or expand for all layers on the first level.
New added buttons in red rectangle:
=> Add Global layer buttons

README.md
Pixelorama has been added to WinGet repository: https://github.com/microsoft/winget-pkgs/pull/170556, it pulls the GitHub release ZIP and installs the package in the system.
This PR adds the info about the required command to install the package via WinGet.
=> Add WinGet as the installation variant

src/UI/Timeline/AnimationTimeline.gd, src/UI/Timeline/AnimationTimeline.tscn
This change fixes layer and frame header in the timeline window on top, so when you scroll down, you can still see the header.
I had to change the container structure to archive that. Also added some seperation between cell container and layer/frame container as I think that looks more clearly when scrolling. However don't know if it fits to what you have in mind.
Also did some other small changes which were needed for this new structure to get a better look (e.g. layer scroll bar is now always visible) and also fixed overlapping cel when selected on bottom.
Tested it under windows 10. Possibly someone can also check if the changes still look good on other operation systems.
=> Set timeline layer and frame header to be fixed on top

src/UI/ColorPickers/ColorPicker.gd
I noticed that the raw values slightly change when you select color through color picker, draw, then pick the color.
This pr fixes this.
https://github.com/user-attachments/assets/7ad6cc40-9f18-452d-bf74-eb852551d947
=> Fixed a colorpicker bug (fixed inconsistent raw values)

project.godot, src/Autoload/Global.gd, src/UI/Tabs.gd
=> Add hotkeys to switch between tabs

src/UI/Dialogs/WindowOpacityDialog.gd, src/UI/UI.gd
Transparency works as expected when Main canvas is part of MAIN window.
but if it gets detached then it behaves un-expectedly in some ways.
- Transparency shader still remains in the Main window (so i temporarily remove it when main canvas is a floating window)
- The transparency didn't work for Floating window (It works now, but only the transparent checker gets modulated, the rest of window is fully transparent which was kinda un-avoidable).
I don't see a reason why a user would decide to detach the Main canvas (Plus enable transparency) but if they do then i hope this will minimize the annoyance
=> somewhat fix transparency for floating window

project.godot
Godot's project settings are configured by default to prevent the system from turning off the screen. While this is helpful for games—such as when playing a cutscene—it’s less useful for creative tools like Pixelorama. When Pixelorama remains open during pauses in the creative process, this behavior can lead to unnecessary power consumption.
Solves
https://github.com/Orama-Interactive/Pixelorama/discussions/1124
Solution description: 
Updated project.godot to set window/energy_saving/keep_screen_on to false (by default is true)
Making use of
https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-display-window-energy-saving-keep-screen-on
> If true, keeps the screen on (even in case of inactivity), so the screensaver does not take over. …
=> Fix: Keep Screen On = False. Allows to turn off screen when app is open and system idle (energy efficient). (one-liner)

src/Autoload/ExtensionsApi.gd
This allows accessing autoloads by placing an `autoload()` method in their related apis
(for the ImportApi, there are actually 2 available autoloads so it slightly deviates from the above naming convention)
this won't cover (as i don't think these are not important, and we don't have a category for it)
- Html5FileExchange
- Keychain
=> Add a way to get autoloads through the api

src/Autoload/Global.gd, src/Preferences/GridPreferences.gd
- Fixed second grid not appearing to be removed when first grid has default values. this was because queue_redraw was not called due to the app thinking nothing had changed.
- fixed reset button of color picker not set correctly when we switch to another grid
- Now, whenever you create a new grid, the new grid will be twice the size of previous grid (and with a different color). this is done because i felt that having all grids being being of same size and color may cause confusion for users when they try to change color of a grid not seeing it's changing (due to being covered by grids above it).
=> Grid patch

project.godot, src/Autoload/Global.gd, src/Autoload/Palettes.gd, src/Autoload/Tools.gd, src/Classes/ImageExtended.gd, src/Classes/Project.gd, src/Main.gd, src/Palette/PaletteGrid.gd, src/UI/Canvas/Canvas.gd, src/UI/Canvas/Canvas.tscn, src/UI/Canvas/color_index.gd, src/UI/TopMenuContainer/TopMenuContainer.gd
An index preview (same as what was used in voxelorama) that displays after the same zoom as pixel grid
NOTE: i attempted to make them visible at all zoom levels but it caused a visual artifact at smaller zoom levels (see video below) so i thought it was best to restrict it up to a given zoom level.
https://github.com/user-attachments/assets/d5bd838f-c25a-4464-a01d-60921b079eb6
- [Index mode] If the color we are drawing is already selected in the palette, then it's index now takes priority (this solves any issues with palettes having multiple instances of the same color)
- [Palettes] Fixed more than one swatch selected in grid if the same color available in an earlier swatch.
- [Index mode] Fixed wrong index drawn when moved to an empty swatch (when we drag and drop to an empty swatch, …
=> Added a way to see index of color (plus bugfixes)

src/Autoload/ExtensionsApi.gd, src/Autoload/Palettes.gd, src/Autoload/Tools.gd, src/Classes/Drawers.gd, src/Classes/ImageExtended.gd, src/Palette/PaletteGrid.gd, src/Tools/BaseDraw.gd, src/Tools/BaseTool.gd, src/Tools/DesignTools/Shading.gd, src/Tools/UtilityTools/ColorPicker.gd, src/Tools/UtilityTools/Text.gd, src/UI/Canvas/color_index.gd, src/UI/ColorPickers/ColorPicker.gd
other changes:
- If drawing over same color in index mode, check and update index as well
- revert an optimization i did in https://github.com/Orama-Interactive/Pixelorama/pull/1143 (commit: https://github.com/Orama-Interactive/Pixelorama/pull/1143/commits/cf32c8812a86c520d1580224f7ed0f2362d590cc)
=> When picking color, ensure that the correct index is selected in palette

src/Autoload/DrawingAlgos.gd
Fixed ellipse draw algos bug from #1137.
Maintainer edit: Closes #1137.
=> Fixed ellipse draw algos bug.

Translations/Translations.pot, src/Tools/DesignTools/Shading.tscn
Adds some missing translation strings I found and fixes a few broken or updated ones.
Also added a colon to the string of a parameter in the editor, for the sake of consistency.
=> Add missing translations strings and fix broken ones

Misc/Linux/com.orama_interactive.Pixelorama.desktop
this line is needed for e.g. GNOME to detect the icon properly upon runtime
=> adding StartupWMClass to the .desktop file

src/Classes/Cels/CelTileMap.gd, src/Tools/BaseDraw.gd, src/Tools/BaseSelectionTool.gd, src/Tools/BaseTool.gd, src/Tools/DesignTools/Bucket.gd, src/Tools/SelectionTools/ColorSelect.gd, src/Tools/SelectionTools/EllipseSelect.gd, src/Tools/SelectionTools/Lasso.gd, src/Tools/SelectionTools/MagicWand.gd, src/Tools/SelectionTools/PaintSelect.gd, src/Tools/SelectionTools/PolygonSelect.gd, src/Tools/SelectionTools/RectSelect.gd, src/Tools/UtilityTools/Move.gd, src/UI/Canvas/Grid.gd, src/UI/Canvas/Selection.gd, src/UI/Canvas/TileModeIndices.gd, src/UI/Timeline/AnimationTimeline.gd
Changing the offset of the tilemap with the move tool when draw tiles mode is active is now possible. I rewrote the tilemap cels to store their cell data in a dictionary instead of an array, allowing for coordinates that are outside the canvas boundaries, including negative coordinates. Right now indices for cells outside of the canvas are not being stored, but this rewrite should make it easier if we want to do this later.
https://github.com/user-attachments/assets/2f8de1af-de65-418d-9929-1135efd46db4
Bugs fixed:
-  Τhe tile preview was sometimes in the wrong place when placing tiles.
- Cloning frames/layers and then editing the cloned tilemap cels no longer breaks the tileset.
=> Change tilemap offset with the move tool

src/UI/Canvas/Gizmos3D.gd
- Fix a bug where axis sometimes got inverted when scaling (fixed by using `normalized()`)
https://github.com/user-attachments/assets/df462902-f7d4-4efc-acb8-932fa183c4bd
- The axis lines have different width depending on their position, this adds a little bit of perspective/depth to the gizmos
- The axis lines stay visible when rotation is active (this is more pleasing to the eye, plus the user can easily get an intuitive understanding of what's going on for symmetrical shapes like cylinder, sphere, etc)
- The X, Y, Z text was too large so `CHAR_SCALE` was decreased from 16 to 10 (This is not shown in the picture)
=> [bugfix + Gizmo] Improve the look of 3d movement gizmos

src/Main.gd
=> Fix Multi Screen Bug

src/Autoload/Global.gd
For first time downloads pixelorama would give error about section not found (because of nonexistent config.ini)
This will check if the section exists, before trying to get it's keys
=> fix section not found (preferences) error

src/Tools/DesignTools/CurveTool.gd, src/Tools/DesignTools/CurveTool.tscn
this mode will allow users to make single Bezier curves similar to Aseprite.
=> Added a single bezier mode in curve tool

src/Autoload/Themes.gd
if the theme was changed without the `theme_font_index` key present in `config.ini`. The wrong font would get chosen (The very first one in the list `Open Sans SemiBold` instead of `Roboto`, which for me is present in the 2nd position.)
i managed to narrow it down to the setter not being triggered on startup if it's entry is not present in config.ini (i assume the code in setter does some initialization which is required for fonts to change properly with theme)
https://github.com/user-attachments/assets/16a50850-536e-41d9-b286-192411381884
Due to the first font being *troublesome*, when it is selected this happens:
=> fix `theme_font_index` setter not being triggered

src/UI/TopMenuContainer/TopMenuContainer.gd
When the (non-pixel) grid is toggled, it immediately updates to show the change.
Before, when the pixel grid was toggled, it would remain visible/hidden until updated by zooming. Add a queue_redraw call to fix.
=> Make pixel grid redraw on visibility toggle

addons/dockable_container/dockable_container.gd
=> Fix #1059 by disabling DragNDropPanel when "Moveable Panels" is disabled

src/UI/CanvasPreviewContainer/CanvasPreviewContainer.gd
This removes the extra steps involved like zooming out the zooming back in.
=> Added ability to double-click on preview to get at the same point on canvas

src/Tools/DesignTools/Bucket.gd, src/Tools/DesignTools/Bucket.tscn
https://github.com/user-attachments/assets/4d710c03-6602-4ed8-aab6-e8326bce12a4
=> Added area fill mode where regions from the merging of all layers is filled

src/Classes/Layers/GroupLayer.gd, src/Classes/ShaderImageEffect.gd
NOTE: This is a performance PR so this would need a little testing, also it should be merged *after* Pixelorama 1.1.2 gets released (just a preference, not a requirement)
Attempt at solving https://github.com/Orama-Interactive/Pixelorama/issues/1250. Boosts the performance of GroupLayers to roughly twice (47% to be precise) it's current state by introducing cache.
- In consecutive generations, when the shader is same, calling `RenderingServer.material_set_shader` again and again (in `generate_image()`) takes up unnecessary computation time (Which makes up most of the 47% time i talked about -- per generation). There is now a way to reuse the material in last generation for the next one.
- when a GroupLayer gets blended, if it has another GroupLayer as child, even if the contents of child …
=> Boost performance of groups with blend_mode != PassThrough

project.godot
The mixed use of physical and Latin-equivalent keycodes for tool shortcuts made some layouts have multiple shortcuts on the same key. Only one of those shortcuts would be used.
Resolves: #1282
=> Fix broken tool shortcuts on some keyboard layouts

src/Autoload/Palettes.gd, src/Palette/PaletteGrid.gd, src/Palette/PalettePanel.gd, src/Palette/PalettePanel.tscn, src/Palette/PaletteSwatch.gd
I noticed some aspects of the palette panel were in need of improvement so this PR addresses these
- Clicking a swatch with Left/Right color now directly add the color to the desired swatch. This saves the trouble of re-arranging the swatch (if required) to the desired place each time a new color is added
- Previously when deleting a color from palette, you'd have to select color and then press delete button. This is fine for removing one or two colors but when removing a chunk of colors, this task becomes cumbersome. **You can now remove colors by `Ctrl + click` on the desired swatch.**
https://github.com/user-attachments/assets/f6effdac-e3ea-4797-8666-b5357cd8c554
https://github.com/user-attachments/assets/e8da0fa1-c616-4db2-8afc-f4ae305124c0
- A new `Auto add colors` option has been …
=> Palette QOL changes

src/Classes/SelectionMap.gd, src/Tools/BaseDraw.gd, src/Tools/DesignTools/Bucket.gd
This introduces two independent optimizations:
Stores existing selection rect as cache and forces `get_selection_rect` in `SelectionMap` to use cache instead. use this to save time when the rect isn't meant to change between repeated calls (e.g see it's use in Bucket tool `_flood_fill`). This causes roughly an 87% boost to the area fill algorithm
when segments were created in `_compute_segments_for_image`
```
for j in image.get_height():
_add_new_segment(j)
```
When we have selection, this ends up adding segments not necessary for calculation. As an optimization, i change it to
```
var y_range = [0, image.get_height()]
_area_end_idx = project.size.y - 1
_area_start_idx = 0
if project.has_selection:
var selection_rect := project.selection_map.get_selection_rect(project)
_area_start_idx = …
```
=> boost speed of bucket in the pressence of selection by about 87%

src/Tools/BaseDraw.gd
Fixes a typo made in https://github.com/Orama-Interactive/Pixelorama/pull/1304
=> Hotfix 1.1.3 bug

src/UI/Timeline/AnimationTimeline.gd
Implements:
> While viewing the animation of some frames under a specific tag (after having checked the animation plays only on frames of the same tag), if you press a frame of another tag you view it for a fraction of a second and then it goes back to showing you the frames of the initial tag. It would be better if it continued playing the animation of the second tag, starting from the frame you just clicked, instead of the first one, since the user clicked the other frame for a reason.
from https://github.com/Orama-Interactive/Pixelorama/discussions/587#discussioncomment-1812691
=> Recalculate start and end points if user deliberately changed the frame during animation.

src/Autoload/DrawingAlgos.gd, src/Autoload/Global.gd, src/Autoload/OpenSave.gd, src/Classes/AnimationTag.gd, src/Classes/ImageEffect.gd, src/Classes/Project.gd, src/Tools/BaseDraw.gd, src/Tools/DesignTools/Bucket.gd, src/Tools/UtilityTools/Move.gd, src/Tools/UtilityTools/Text.gd, src/UI/Buttons/BrushesPopup.gd, src/UI/Canvas/ReferenceImages.gd, src/UI/Canvas/Selection.gd, src/UI/Dialogs/ImageEffects/FlipImageDialog.gd, src/UI/Dialogs/ImportTagDialog.gd, src/UI/Dialogs/ProjectProperties.gd, src/UI/PerspectiveEditor/PerspectiveEditor.gd, src/UI/Timeline/AnimationTagUI.gd, src/UI/Timeline/AnimationTimeline.gd, src/UI/Timeline/CelButton.gd, src/UI/Timeline/FrameProperties.gd, src/UI/Timeline/LayerEffects/LayerEffectButton.gd, src/UI/Timeline/LayerEffects/LayerEffectsSettings.gd, src/UI/Timeline/LayerProperties.gd, src/UI/Timeline/TagProperties.gd, src/UI/TopMenuContainer/TopMenuContainer.gd
An old commit for 0.4: https://github.com/Orama-Interactive/Pixelorama/commit/8fadacdf123f89ba8430b8e02312e148df0019bc introduced the`undos` variable at 3 important places in Canvas.gd
These were later removed/replaced by better alternatives (see below)
This PR removes all the other remaining traces of `undos` variable.
(The 3 important places and the commits that remove them)
---
```
#. .. it means that the cursor was outside the canvas. Then, ...
if Input.is_action_pressed("left_mouse") || Input.is_action_pressed("right_mouse"):
if (mouse_in_canvas && Global.undos < Global.undo_redo.get_version()) || is_making_line:
mouse_pressed = true
```
The need for this section was removed by https://github.com/Orama-Interactive/Pixelorama/pull/253/commits/bda9e6267dbde2c9c3413bbaf7391c4639a84cb2#di …
=> Removed the `Project.undos` variable 
